version: '3.1'
networks:
  app-tier:
    driver: bridge
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-tier
    volumes:
      - "mongo-volume:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 18081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    networks:
      - app-tier
  # api:
  #   container_name: chat_box_english
  #   image: "node:10.18.0"
  #   user: "root"
  #   restart: always
  #   ports:
  #     - "8200:8000"
  #   working_dir: /home/node/app
  #   volumes:
  #     - ./:/home/node/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #   command: "npm run start:dev"
  #   networks:
  #     - app-tier

  adminer:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      - 18082:80
    networks:
      - app-tier
    depends_on:
      - mongo

volumes:
  mongo-volume:
